In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt


In [2]:
img= cv2.imread('/content/zero.png')

In [3]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [197 197 197]
  [  0   0   0]
  ...
  [  0   0   0]
  [196 196 196]
  [255 255 255]]

 [[255 255 255]
  [164 164 164]
  [  0   0   0]
  ...
  [  0   0   0]
  [164 164 164]
  [255 255 255]]

 [[255 255 255]
  [235 235 235]
  [164 164 164]
  ...
  [164 164 164]
  [235 235 235]
  [255 255 255]]]


In [4]:
sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)

In [5]:
print(sobelx)

[[[    0.     0.     0.]
  [    0.     0.     0.]
  [    0.     0.     0.]
  ...
  [    0.     0.     0.]
  [    0.     0.     0.]
  [    0.     0.     0.]]

 [[    0.     0.     0.]
  [    0.     0.     0.]
  [    0.     0.     0.]
  ...
  [    0.     0.     0.]
  [    0.     0.     0.]
  [    0.     0.     0.]]

 [[    0.     0.     0.]
  [    0.     0.     0.]
  [    0.     0.     0.]
  ...
  [    0.     0.     0.]
  [    0.     0.     0.]
  [    0.     0.     0.]]

 ...

 [[    0.     0.     0.]
  [-1020. -1020. -1020.]
  [ -230.  -230.  -230.]
  ...
  [  228.   228.   228.]
  [ 1020.  1020.  1020.]
  [    0.     0.     0.]]

 [[    0.     0.     0.]
  [ -856.  -856.  -856.]
  [ -400.  -400.  -400.]
  ...
  [  398.   398.   398.]
  [  856.   856.   856.]
  [    0.     0.     0.]]

 [[    0.     0.     0.]
  [ -692.  -692.  -692.]
  [ -406.  -406.  -406.]
  ...
  [  404.   404.   404.]
  [  692.   692.   692.]
  [    0.     0.     0.]]]


In [6]:
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)

In [7]:
print(sobely)

[[[   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 ...

 [[ -82.  -82.  -82.]
  [ -82.  -82.  -82.]
  [-246. -246. -246.]
  ...
  [-246. -246. -246.]
  [ -82.  -82.  -82.]
  [ -82.  -82.  -82.]]

 [[  76.   76.   76.]
  [ 240.  240.  240.]
  [ 398.  398.  398.]
  ...
  [ 400.  400.  400.]
  [ 242.  242.  242.]
  [  78.   78.   78.]]

 [[   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]]
